spring:
  application:
    name: card-address-validation

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  cache:
    type: redis

provider:
  cep:
    base-url: ${PROVIDER_CEP_BASE_URL}
    connect-timeout: 2s
    read-timeout: 2s

cache:
  cep:
    ttl: ${CACHE_CEP_TTL}

resilience4j:
  circuitbreaker:
    instances:
      cepProvider:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - com.bank.cardaddressvalidation.domain.ProviderUnavailableException

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  health:
    circuitbreakers:
      enabled: true
